name: PR Trip API

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - 'apis/trips/**'    
      - '.github/workflows/golang.yml'
      - '.github/workflows/golang-deploy.yml'

defaults:
  run:
    working-directory: apis/trips

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write    

    steps:
    - uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'go'
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./tests 

    # Execute the create-an-issue task if the previous task fails
    - name: Create Issue
      if: failure() 
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{ env.GITHUB_WORKFLOW }}
        filename: .github/ISSUE_TEMPLATE_HACK.md        

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1