name: PR Trip API

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - 'apis/trips/**'    
      - '.github/workflows/golang.yml'
      - '.github/workflows/golang-deploy.yml'

defaults:
  run:
    working-directory: apis/trips

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.11.1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./tests 
