name: node-PR

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'apis/userprofile/**'    
      - '.github/workflows/node-PR.yml'
defaults:
  run:
    working-directory: apis/userprofile
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js v8.x
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: install dependencies
      run: npm install
    - name: Test program
      run: npm test
    # Execute the create-an-issue task if the previous task fails
    - name: Create Issue
      if: failure() 
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{ env.GITHUB_WORKFLOW }}
        filename: .github/ISSUE_TEMPLATE_HACK.md
